//
//  ShowdownData.swift
//  PKDex
//
//  Loads the vendored @smogon/calc data tables (generated by
//  tools/gen_showdown_data.ts into showdown-champions-data.json) and exposes
//  them through the `ShowdownGeneration` provider the mechanics read from.
//  MIT — see PKDex/ShowdownPort-NOTES.md.
//

import Foundation

/// Champions ("gen 0") data provider backed by the bundled JSON. One shared
/// instance; the ~140 KB table is parsed once and keyed by `toID`.
final class ShowdownGen0: ShowdownGeneration {
    static let shared = ShowdownGen0()

    let num = 0
    private let speciesByID: [ShowdownID: ShowdownSpecies]
    private let movesByID: [ShowdownID: ShowdownMoveData]
    /// attackingType -> (defendingType -> multiplier)
    private let typechart: [ShowdownType: [ShowdownType: Double]]

    private struct Payload: Decodable {
        let generation: Int
        let species: [String: ShowdownSpecies]
        let moves: [String: ShowdownMoveData]
        let typechart: [String: [String: Double]]
    }

    private init() {
        guard let url = Bundle.main.url(forResource: "showdown-champions-data", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let payload = try? JSONDecoder().decode(Payload.self, from: data)
        else {
            self.speciesByID = [:]; self.movesByID = [:]; self.typechart = [:]
            print("[ShowdownGen0] missing/invalid showdown-champions-data.json")
            return
        }
        self.speciesByID = Dictionary(payload.species.map { (toID($0.key), $0.value) },
                                      uniquingKeysWith: { a, _ in a })
        self.movesByID = Dictionary(payload.moves.map { (toID($0.key), $0.value) },
                                    uniquingKeysWith: { a, _ in a })
        var chart: [ShowdownType: [ShowdownType: Double]] = [:]
        for (atkName, row) in payload.typechart {
            guard let atk = ShowdownType(rawValue: atkName) else { continue }
            var inner: [ShowdownType: Double] = [:]
            for (defName, mult) in row {
                if let def = ShowdownType(rawValue: defName) { inner[def] = mult }
            }
            chart[atk] = inner
        }
        self.typechart = chart
    }

    func species(_ id: ShowdownID) -> ShowdownSpecies? { speciesByID[id] }
    func move(_ id: ShowdownID) -> ShowdownMoveData? { movesByID[id] }

    func effectiveness(_ attacking: ShowdownType, _ defending: ShowdownType) -> Double {
        typechart[attacking]?[defending] ?? 1.0
    }
}
